FROM pmallozzi/ros:catkin

RUN apt-get update && apt-get install -y \
    ros-kinetic-turtlebot \
    ros-kinetic-turtlebot-apps \
    ros-kinetic-turtlebot-interactions \
    ros-kinetic-turtlebot-simulator